DROP SCHEMA IF EXISTS LIBRARY CASCADE;

CREATE SCHEMA LIBRARY;

CREATE TABLE LIBRARY.TYPE_OF_OPERATION (
    OPERATION_DK            INTEGER             PRIMARY KEY,
    OPERATION_NM            VARCHAR(20)         NOT NULL
);

CREATE TABLE LIBRARY.WORKER (
    WORKER_ID       INTEGER         PRIMARY KEY,
    SURNAME_NM      VARCHAR(50)     NOT NULL,
    NAME_NM         VARCHAR(50)     NOT NULL,
    PATRONYMIC_NM   VARCHAR(50)     NOT NULL,
    PASSPORT_NO     VARCHAR(10)     NOT NULL,
    POSITION_TXT    VARCHAR(100)    NOT NULL,
    CARD_NO         VARCHAR(16)     NOT NULL,
    PHONE_NO        VARCHAR(15)     NOT NULL,
    ADDRESS_TXT     TEXT            NOT NULL,
    NOTE_TXT        TEXT,
    START_DT        DATE            NOT NULL,
    FINISH_DT       DATE            NOT NULL DEFAULT '9999-12-31'
);

CREATE TABLE LIBRARY.READER (
    READER_ID           INTEGER         PRIMARY KEY,
    SURNAME_NM          VARCHAR(50)     NOT NULL,
    NAME_NM             VARCHAR(50)     NOT NULL,
    PATRONYMIC_NM       VARCHAR(50)     NOT NULL,
    PHONE_NO            VARCHAR(15)     NOT NULL,
    BIRTHDAY_DT         DATE            NOT NULL,
    ADDRESS_TXT         TEXT            NOT NULL,
    NOTE_TXT            TEXT,
    REGISTRATION_DT     DATE            NOT NULL,
    PASSPORT_NO         VARCHAR(10)     NOT NULL
);

CREATE TABLE LIBRARY.SERVICE (
    SERVICE_ID              INTEGER         PRIMARY KEY,
    READER_ID               INTEGER         REFERENCES LIBRARY.READER(READER_ID),
    WORKER_ID               INTEGER         REFERENCES LIBRARY.WORKER(WORKER_ID),
    OPERATION_DK            INTEGER         REFERENCES LIBRARY.TYPE_OF_OPERATION(OPERATION_DK),
    BUILDING_NO             INTEGER         NOT NULL,
    ROOM_NO                 INTEGER         NOT NULL,
    SERVICE_DT              DATE            NOT NULL
);

CREATE TABLE LIBRARY.TYPE_OF_BOOK (
    TYPE_ID             INTEGER         PRIMARY KEY,
    TITLE_NM            VARCHAR(100)    NOT NULL,
    AUTHOR_NM           VARCHAR(100)    NOT NULL,
    PUBLISHING_NM       VARCHAR(100)    NOT NULL,
    PUBLISHING_YEAR_DT  INTEGER         NOT NULL,
    GENRE_TXT           VARCHAR(50)     NOT NULL,
    PAGE_CNT            INTEGER         NOT NULL,
    AGE_LIMIT_NO        INTEGER         NOT NULL,
    DESCRIPTION_TXT     TEXT            
);

CREATE TABLE LIBRARY.BOOK (
    BOOK_ID                 INTEGER         PRIMARY KEY,
    TYPE_ID                 INTEGER         REFERENCES LIBRARY.TYPE_OF_BOOK(TYPE_ID),
    BUILDING_NO             INTEGER         NOT NULL,
    ROOM_NO                 INTEGER         NOT NULL,
    SECTION_NO              INTEGER         NOT NULL,
    BOOKCASE_NO             INTEGER         NOT NULL,
    BOOK_CONDITION_TXT      TEXT            NOT NULL,
    INCOME_DT               DATE            NOT NULL,
    COVER_TXT               TEXT            NOT NULL
);

CREATE TABLE LIBRARY.SERVICE_X_BOOK (
    BOOK_ID         INTEGER         REFERENCES LIBRARY.BOOK(BOOK_ID),
    SERVICE_ID      INTEGER         REFERENCES LIBRARY.SERVICE(SERVICE_ID)
);

CREATE TABLE LIBRARY.WISH_LIST (
    READER_ID       INTEGER         REFERENCES LIBRARY.READER(READER_ID),
    TYPE_ID         INTEGER         REFERENCES LIBRARY.TYPE_OF_BOOK(TYPE_ID),
    SERVICE_ID      INTEGER         REFERENCES LIBRARY.SERVICE(SERVICE_ID)
);
